/// 所有内容 JSON 资源的静态注册表。
///
/// 按 "模块/学科" 键分组，支持精确按需加载。
/// 新增内容文件时需同步更新此注册表。
library;

/// 按 "模块" 或 "模块/学科" 分组的 JSON 资源路径。
///
/// 加载时先查精确键 "module/subject"，找不到再查 "module"。
const Map<String, List<String>> assetRegistry = {
  // ── 智育 · 数学 ──────────────────────────────────────────────
  'intellect/math': [
    'assets/content/intellect/math/grade1.json',
    'assets/content/intellect/math/grade1_batch3.json',
    'assets/content/intellect/math/grade1_extra.json',
    'assets/content/intellect/math/grade1_more.json',
    'assets/content/intellect/math/grade2.json',
    'assets/content/intellect/math/grade2_extra.json',
    'assets/content/intellect/math/grade2_more.json',
    'assets/content/intellect/math/grade3.json',
    'assets/content/intellect/math/grade3_batch3.json',
    'assets/content/intellect/math/grade3_extra.json',
    'assets/content/intellect/math/grade3_more.json',
    'assets/content/intellect/math/grade4.json',
    'assets/content/intellect/math/grade4_extra.json',
    'assets/content/intellect/math/grade4_more.json',
    'assets/content/intellect/math/grade5.json',
    'assets/content/intellect/math/grade5_batch3.json',
    'assets/content/intellect/math/grade5_extra.json',
    'assets/content/intellect/math/grade5_more.json',
    'assets/content/intellect/math/grade6.json',
    'assets/content/intellect/math/grade6_batch3.json',
    'assets/content/intellect/math/grade6_extra.json',
    'assets/content/intellect/math/grade6_more.json',
    'assets/content/intellect/math/grade7.json',
    'assets/content/intellect/math/grade7_extra.json',
    'assets/content/intellect/math/grade7_more.json',
    'assets/content/intellect/math/grade8.json',
    'assets/content/intellect/math/grade8_batch3.json',
    'assets/content/intellect/math/grade8_extra.json',
    'assets/content/intellect/math/grade8_more.json',
    'assets/content/intellect/math/grade9.json',
    'assets/content/intellect/math/grade9_batch3.json',
    'assets/content/intellect/math/grade9_extra.json',
    'assets/content/intellect/math/grade9_more.json',
  ],

  // ── 智育 · 语文 ──────────────────────────────────────────────
  'intellect/chinese': [
    'assets/content/intellect/chinese/lower.json',
    'assets/content/intellect/chinese/lower_batch3.json',
    'assets/content/intellect/chinese/lower_extra.json',
    'assets/content/intellect/chinese/middle.json',
    'assets/content/intellect/chinese/middle_batch3.json',
    'assets/content/intellect/chinese/middle_extra.json',
    'assets/content/intellect/chinese/upper.json',
    'assets/content/intellect/chinese/upper_extra.json',
    'assets/content/intellect/chinese/junior.json',
    'assets/content/intellect/chinese/junior_batch3.json',
    'assets/content/intellect/chinese/junior_extra.json',
  ],

  // ── 智育 · 英语 ──────────────────────────────────────────────
  'intellect/english': [
    'assets/content/intellect/english/starter.json',
    'assets/content/intellect/english/starter_extra.json',
    'assets/content/intellect/english/basic.json',
    'assets/content/intellect/english/basic_batch3.json',
    'assets/content/intellect/english/basic_extra.json',
    'assets/content/intellect/english/intermediate.json',
    'assets/content/intellect/english/intermediate_batch3.json',
    'assets/content/intellect/english/intermediate_extra.json',
    'assets/content/intellect/english/advanced.json',
    'assets/content/intellect/english/advanced_batch3.json',
    'assets/content/intellect/english/advanced_extra.json',
  ],

  // ── 科技 ─────────────────────────────────────────────────────
  'tech': [
    'assets/content/tech/programming/blocks_questions.json',
    'assets/content/tech/programming/blocks_extra.json',
    'assets/content/tech/programming/python_questions.json',
    'assets/content/tech/programming/python_extra.json',
    'assets/content/tech/programming/algorithm_questions.json',
    'assets/content/tech/programming/algorithm_extra.json',
    'assets/content/tech/programming/computational_thinking.json',
    'assets/content/tech/ai_intro/what_is_ai.json',
    'assets/content/tech/ai_intro/ml_basics.json',
    'assets/content/tech/virtual_lab/mechanics.json',
    'assets/content/tech/virtual_lab/optics.json',
    'assets/content/tech/virtual_lab/circuits.json',
    'assets/content/tech/virtual_lab/biology.json',
    'assets/content/tech/virtual_lab/chemistry.json',
    'assets/content/tech/virtual_lab/earth_science.json',
    'assets/content/tech/aerospace/rockets.json',
    'assets/content/tech/aerospace/solar_system.json',
    'assets/content/tech/timeline/ancient.json',
    'assets/content/tech/timeline/industrial.json',
    'assets/content/tech/timeline/information.json',
    'assets/content/tech/timeline/future.json',
    'assets/content/tech/science/physics_basics.json',
    'assets/content/tech/science/physics_extra.json',
    'assets/content/tech/science/chemistry_basics.json',
    'assets/content/tech/science/chemistry_extra.json',
    'assets/content/tech/science/biology_basics.json',
    'assets/content/tech/science/earth_space.json',
    'assets/content/tech/new_tech/emerging.json',
  ],

  // ── 逻辑 ─────────────────────────────────────────────────────
  'logic': [
    'assets/content/logic/pattern.json',
    'assets/content/logic/pattern_advanced.json',
    'assets/content/logic/pattern_batch2.json',
    'assets/content/logic/pattern_extra.json',
    'assets/content/logic/deduction.json',
    'assets/content/logic/deduction_batch2.json',
    'assets/content/logic/deduction_extra.json',
    'assets/content/logic/spatial.json',
    'assets/content/logic/spatial_batch2.json',
    'assets/content/logic/spatial_extra.json',
    'assets/content/logic/strategy.json',
    'assets/content/logic/strategy_batch2.json',
    'assets/content/logic/strategy_extra.json',
    'assets/content/logic/twenty_four.json',
    'assets/content/logic/math_puzzles.json',
    'assets/content/logic/reasoning_fun.json',
  ],

  // ── 通识 ─────────────────────────────────────────────────────
  'general': [
    'assets/content/general/animals_plants.json',
    'assets/content/general/art.json',
    'assets/content/general/art_extra.json',
    'assets/content/general/body_health.json',
    'assets/content/general/china_geography.json',
    'assets/content/general/chinese_culture.json',
    'assets/content/general/chinese_provinces.json',
    'assets/content/general/countries.json',
    'assets/content/general/famous_scientists.json',
    'assets/content/general/geography.json',
    'assets/content/general/history.json',
    'assets/content/general/inventions.json',
    'assets/content/general/life_skills.json',
    'assets/content/general/life_skills_extra.json',
    'assets/content/general/math_fun.json',
    'assets/content/general/science_basics.json',
    'assets/content/general/sports.json',
    'assets/content/general/world_geography.json',
    'assets/content/general/world_history.json',
  ],

  // ── 德育 ─────────────────────────────────────────────────────
  'moral': [
    'assets/content/moral/quotes.json',
    'assets/content/moral/quotes_classics.json',
    'assets/content/moral/quotes_more.json',
    'assets/content/moral/stories/biography.json',
    'assets/content/moral/stories/fable.json',
    'assets/content/moral/stories/idiom.json',
    'assets/content/moral/stories/modern.json',
    'assets/content/moral/stories/science_hero.json',
    'assets/content/moral/stories/world_fable.json',
    'assets/content/moral/tradition/classics.json',
    'assets/content/moral/tradition/festivals.json',
    'assets/content/moral/values/attitudes.json',
    'assets/content/moral/values/core_values.json',
    'assets/content/moral/values/daily_wisdom.json',
    'assets/content/moral/values/doing_things_right.json',
    'assets/content/moral/values/effective_learning.json',
    'assets/content/moral/values/ethics_scenarios.json',
    'assets/content/moral/values/life_outlook.json',
    'assets/content/moral/values/life_principles.json',
    'assets/content/moral/values/role_models.json',
    'assets/content/moral/values/values_questions.json',
    'assets/content/moral/values/values_stories.json',
    'assets/content/moral/values/worldview.json',
  ],

  // ── 好词好句 ─────────────────────────────────────────────────
  'words': [
    'assets/content/words/poetry_classical.json',
    'assets/content/words/poetry_extra.json',
    'assets/content/words/prose_modern.json',
    'assets/content/words/prose_extra.json',
    'assets/content/words/composition_phrases.json',
    'assets/content/words/composition_extra.json',
    'assets/content/words/famous_quotes.json',
    'assets/content/words/idiom_usage.json',
    'assets/content/words/idiom_extra.json',
    'assets/content/words/ancient_wisdom.json',
    'assets/content/words/nature.json',
    'assets/content/words/reading_excerpts.json',
  ],
};
